@startuml
class "DIP" {
    - APIKey: String
    - URLBase: String
    - numFoundCache: Dictionary<string, int>
    - electroalPeriods: Dictionary<int, string>
    - ToQueryString(args: NameValueCollection ): String
    - SetDefaultParams (term: string, electionPeriod: int[]): NameValueCollection
    - Request(args: NameValuecollection): dynamic
    - GetMentions(term: string, electionPeriod: int[]): List
    + DIP() << constructor >>
    + GetResults(term: string, electionPeriod: Int[]): Int 
    + GetResults(term: string): Int 
    + GetRelevance(GroupMode: mode, term: string): Dictionary<string, int>
    + GetRelevance(GroupMode: mode, term: string, electionPeriod: int[]): Dictionary<string, int>
}

enum GroupMode{
  Year
  Month
}
@enduml