name: .NET

on: push

jobs:
  build:

    name: Build And Test Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: tests/test/TestResults/coverage.info 

  documentation:
    name: Generate Documentation
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Update Wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: "julian@juliankeppler.de"
        GH_NAME: github_actions
    - name: Update Documentation.md
      uses: EndBug/add-and-commit@v7
      with:
          default_author: github_actions
          add: 'wiki/Documentation.md'
          message: 'Generate Documentation'
